# Generated by Django 5.1.4 on 2024-12-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityQuery',
            new_name='CitySearchHistory',
        ),
        migrations.RenameField(
            model_name='citysearchhistory',
            old_name='query_time',
            new_name='searched_at',
        ),
    ]
